import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const steps=['Upload candidates','Resume + JD review','GitHub analysis','Recruiter review','Test results','Final review'];
function App(){
 const[c,setC]=useState([]),[jd,setJd]=useState(''),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[details,setDetails]=useState([]),[interviewStart,setInterviewStart]=useState(''),[duration,setDuration]=useState(30),[gap,setGap]=useState(10);
 const load=()=>fetch(API+'/candidates').then(r=>r.json()).then(setC); useEffect(()=>{load()},[]);
 const run=async(fn)=>{setBusy(true);setMsg('');try{await fn()}catch(e){setMsg('Error: '+e.message)}finally{setBusy(false);load()}};
 const uploadCandidates=e=>run(async()=>{const f=e.target.files[0];if(!f)return;let x=new FormData();x.append('file',f);let r=await fetch(API+'/candidates/upload',{method:'POST',body:x});let d=await r.json();if(!r.ok)throw Error(d.detail||'Upload failed');setMsg(`${d.added} added, ${d.skipped} skipped (${d.duplicate_in_file} duplicate in file, ${d.already_exists} already stored)`);setStep(1)});
 const resumeStep=()=>run(async()=>{if(!jd.trim())throw Error('Paste the job description first');let x=new FormData();x.append('job_description',jd);let r=await fetch(API+'/steps/resume-jd',{method:'POST',body:x});let d=await r.json();if(!r.ok)throw Error(d.detail||'Evaluation failed');setDetails(d.results||[]);setMsg('Resume/JD evaluation completed. Review scores below.');setStep(2)});
 const githubStep=()=>run(async()=>{let r=await fetch(API+'/steps/github',{method:'POST'});let d=await r.json();if(!r.ok)throw Error(d.detail||'GitHub analysis failed');setDetails(d.results||[]);setMsg('GitHub analysis and screening scores completed.');setStep(3)});
 const uploadTests=e=>run(async()=>{const f=e.target.files[0];if(!f)return;let x=new FormData();x.append('file',f);let r=await fetch(API+'/tests/upload',{method:'POST',body:x});let d=await r.json();if(!r.ok)throw Error(d.detail||'Test upload failed');setMsg(`${d.updated} test results updated`);setStep(5)});
 const autoSchedule=()=>run(async()=>{if(!interviewStart)throw Error('Choose the first interview date and time');const local=new Date(interviewStart);const offset=-local.getTimezoneOffset();const sign=offset>=0?'+':'-';const pad=n=>String(Math.abs(n)).padStart(2,'0');const iso=interviewStart+':00'+sign+pad(Math.floor(Math.abs(offset)/60))+':'+pad(Math.abs(offset)%60);let r=await fetch(API+'/interviews/schedule-automatic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_iso:iso,duration_minutes:Number(duration),gap_minutes:Number(gap),statuses:['selected','interview']})});let d=await r.json();if(!r.ok)throw Error(d.detail||'Automatic scheduling failed');setDetails(d.results||[]);setMsg(`${d.scheduled} of ${d.total} interviews scheduled. Google Calendar sends Meet invitations automatically.`)});
 const edit=async(x,field)=>{let label=field.replaceAll('_',' ');let raw=prompt(`Edit ${label} for ${x.name}`,x[field]??'');if(raw===null)return;let value=['cgpa','resume_score','github_score','screening_score','logical_score','coding_score','final_score'].includes(field)?Number(raw):raw;await run(async()=>{let r=await fetch(API+`/candidates/${x.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[field]:value})});if(!r.ok)throw Error('Could not save edit');setMsg(`${label} updated by recruiter/admin`)})};
 const counts=useMemo(()=>({all:c.length,short:c.filter(x=>['shortlisted','selected','test_sent','interview','interview_scheduled'].includes((x.status||'').toLowerCase())).length,interview:c.filter(x=>['interview','interview_scheduled'].includes((x.status||'').toLowerCase())).length}),[c]);
 return <main><header><div><b>myNachiketa</b><span> Hiring Workflow</span></div><small>Admin / Recruiter Console</small></header>
 <section className="hero"><div><span className="eyebrow">SEQUENTIAL SCREENING</span><h1>Review every decision before the next step.</h1><p>Upload candidate data, run each evaluation one at a time, inspect the result, edit recruiter-controlled scores/status, then continue.</p></div><div className="stats"><b>{counts.all}</b><small>Candidates</small><b>{counts.short}</b><small>Shortlisted</small><b>{counts.interview}</b><small>Interviews</small></div></section>
 <nav className="stepper">{steps.map((s,i)=><button key={s} className={i===step?'active':i<step?'done':''} onClick={()=>setStep(i)}><span>{i+1}</span>{s}</button>)}</nav>
 {msg&&<div className="notice">{msg}</div>}
 <section className="workspace">
  {step===0&&<div className="card focus"><h2>1. Upload candidate dataset</h2><p>Supported: CSV, XLSX, XLS. Required columns: name, email, college, branch, cgpa, best_ai_project, research_work, github_profile, resume_link.</p><input type="file" accept=".csv,.xlsx,.xls" onChange={uploadCandidates}/></div>}
  {step===1&&<div className="card focus"><h2>2. Resume + Job Description evaluation</h2><p>Paste the job description. The current MVP evaluates candidate text/project/research information against it.</p><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste complete job description here..."/><button disabled={busy||!c.length} onClick={resumeStep}>{busy?'Processing…':'Run resume/JD evaluation'}</button></div>}
  {step===2&&<div className="card focus"><h2>3. GitHub repository analysis</h2><p>Analyzes each public GitHub profile, then calculates the screening score. You can inspect and edit the result before proceeding.</p><button disabled={busy||!c.length} onClick={githubStep}>{busy?'Analyzing…':'Analyze GitHub profiles'}</button></div>}
  {step===3&&<div className="card focus"><h2>4. Recruiter/Admin review</h2><p>Click any underlined value in the table to override it. When review is complete, continue to test results.</p><button onClick={()=>setStep(4)}>Approve review & continue</button></div>}
  {step===4&&<div className="card focus"><h2>5. Upload test results</h2><p>CSV/Excel columns: email, test_la, test_code. Final score and interview eligibility are calculated after upload.</p><input type="file" accept=".csv,.xlsx,.xls" onChange={uploadTests}/></div>}
  {step===5&&<div className="card focus"><h2>6. Final recruiter review & interview scheduling</h2><p>Set qualified candidates to <b>selected</b> (or keep <b>interview</b>). The counters update immediately after the saved status reloads. Then choose the first interview time; candidates are scheduled by final score with separate Google Meet links and Calendar invitations.</p><div className="schedulegrid"><label>First interview<input type="datetime-local" value={interviewStart} onChange={e=>setInterviewStart(e.target.value)}/></label><label>Duration (minutes)<input type="number" min="10" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Gap (minutes)<input type="number" min="0" value={gap} onChange={e=>setGap(e.target.value)}/></label></div><button disabled={busy} onClick={autoSchedule}>{busy?'Scheduling…':'Schedule selected interviews automatically'}</button><button className="secondary" onClick={load}>Refresh results</button></div>}
 </section>
 <section className="card table"><div className="rowtitle"><div><h2>Step results</h2><p>Editable fields are underlined.</p></div><button className="secondary" onClick={load}>Refresh</button></div><table><thead><tr><th>Candidate</th><th>CGPA</th><th>Resume/JD</th><th>GitHub</th><th>Screening</th><th>Logical</th><th>Coding</th><th>Final</th><th>Status</th></tr></thead><tbody>{c.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.email}</small></td>{['cgpa','resume_score','github_score','screening_score','logical_score','coding_score','final_score'].map(f=><td key={f}><button className="editable" onClick={()=>edit(x,f)}>{Number(x[f]||0).toFixed(f==='cgpa'?2:1)}</button></td>)}<td><button className={'pill '+x.status} onClick={()=>edit(x,'status')}>{x.status}</button></td></tr>)}</tbody></table>{!c.length&&<div className="empty">No candidates yet. Start with Step 1.</div>}</section>
 {details.length>0&&<section className="card detail"><h2>Latest processing details</h2><pre>{JSON.stringify(details,null,2)}</pre></section>}
 </main>}
createRoot(document.getElementById('root')).render(<App/>);
